
databases:
  # UPDATE THESE IF URLS CHANGE OR TO SET SPECIFIC VERSIONS
  interpro:
    tax_base_url: "https://www.ebi.ac.uk:443/interpro/api/taxonomy/uniprot/protein/entry/InterPro/{prot_id}/?page_size=200"
  riboswitch:
    # not currenlty used
    base_url: "https://riboswitch.ribocentre.org/downloads/sequences"
  gtdb:
    gtdb_bacteria_tree_url: "https://data.gtdb.ecogenomic.org/releases/latest/bac120.tree"
    gtdb_bacteria_metadata_url: "https://data.gtdb.ecogenomic.org/releases/latest/bac120_metadata.tsv.gz"
  ncbi:
    batch_size: 50
  rfam:
    rfam_cm_url: "https://ftp.ebi.ac.uk/pub/databases/Rfam/CURRENT/Rfam.cm.gz"
    rfam_genome_index_url: "https://ftp.ebi.ac.uk/pub/databases/Rfam/CURRENT/Rfam.full_region.gz"
  entrez:
    email: "dacda462@student.otago.ac.nz"
# dirs:
#   data: "resources"
#   genomes: "resources/genomes"
#   results: "results"

# InterPro
interpro:
  target_interpro_ids: 
  #- "IPR007024"
  - "IPR010079"

# Taxonomy filtering
taxonomy:
  #target_taxonomic_node: "36.0:f__Burkholderiaceae_C"
  target_taxonomic_node: "74.0:f__Bacillaceae"
  completeness_threshold: 99.9
  contamination_threshold: 1

# HMMER
hmmer:
  e: "1e-5"

flanking:
  upstream: -1
  downstream: -1
  length_threshold: 35 # find biological reasoning
  gc_content_threshold: 0 # 

cmfinder:
  evalue_threshold: 0.1 # higher for now to be more inclusive, can be refined later
  min_sequence_count: 5  # Minimum sequences needed to run CMfinder
  min_refinement_sequences: 3  # Minimum sequences needed for refinement step
  docker_image: "cmfinder:latest"
  docker_platform: "linux/amd64"
  threads:
    initial_discovery: 4
    calibration: 4
    homolog_search: 4
    refinement: 4
    annotation: 4
  resources:
    initial_discovery_mb: 8000
    initial_discovery_runtime: 240
    calibration_mb: 8000
    calibration_runtime: 120
    homolog_search_mb: 8000
    homolog_search_runtime: 120
    refinement_mb: 16000
    refinement_runtime: 360
    annotation_mb: 8000
    annotation_runtime: 120

clustering:
  mmseqs2:
  # set these parameters based on the desired clustering sensitivity and specificity for finding distant homologs which can be small domains of entire proteins
    sensitivity: 7.5
    min_seq_id: 0.25
    coverage_threshold: 0.2
    cov_mode: 3
    cluster_mode: 1
    threads: 4

controls:
  cds_search_area: 1000
  min_cluster_size: 5
  rfam_families:
    - "RF00050" # FMN riboswitch